from models.ticket import Ticket

#short discription
# def get_dummy_ticket() -> Ticket:
#     return Ticket(
#         ticket_id="ADAS-1423",
#         summary="Lane Keeping Assist drifts to the left",
#         description="""
# Vehicle continuously drifts towards the left after driving
# for approximately 15 minutes.

# Issue reproduced in SIL and HIL.

# Expected Behaviour:
# Vehicle should remain centered within the lane.

# Actual Behaviour:
# Vehicle slowly deviates towards the left without steering correction.

# Environment:
# • Vehicle Speed : 80 km/h
# • Weather : Clear
# • Road Type : Highway
# • Software Version : v2.4.1
# """,
#         comments=[
#             "Customer reported issue during highway testing.",
#             "Issue successfully reproduced in SIL.",
#             "No CAN communication errors observed.",
#             "Camera calibration verified successfully.",
#             "Possible steering controller issue.",
#             "Need algorithm team investigation."
#         ],
#         attachments=[
#             "sample_images/lka_dashboard.png",
#             "sample_images/lka_camera_view.png",
#             "sample_images/graphic.png"

#         ]
#     )

#long discription

def get_dummy_ticket() -> Ticket:
    return Ticket(
        ticket_id="ADAS-1423",
        summary="Lane Keeping Assist drifts to the left",
        description="""
Issue reported by Nissan Japan validation team.

The Lane Keeping Assist (LKA) function is not maintaining the vehicle within the lane during long highway driving scenarios.

The issue has been reproduced multiple times during SIL and HIL validation using the latest software build.

Vehicle Information
-----------------------------
Platform : CMF-C
Project : ADAS Gen-3
ECU : ADAS Domain Controller
Software Version : v3.8.2
Build : 2026.07.18_RC2
Environment : SIL / HIL
Camera Calibration : PASS
Radar Status : PASS
Vehicle Speed : 80 km/h

Issue Description
-----------------------------
Vehicle starts driving normally with LKA enabled.

After approximately 15 minutes of continuous highway driving, the vehicle gradually starts drifting towards the left lane marking.

The steering correction generated by the LKA controller becomes weaker over time and eventually stops correcting the lane offset.

Around the same time, the instrument cluster displays the warning:

"Lane Keeping Assist Fault - Please Take Control"

Driver takeover is required.

The issue is reproducible on multiple test benches.

Observed Behaviour
-----------------------------
• Vehicle drifts continuously to the left
• LKA warning displayed
• LKA state changes from ACTIVE to FAULT
• Driver torque override required
• No ECU reset observed
• No CAN timeout detected
• Camera image appears normal
• Radar objects detected correctly
• No sensor diagnostic trouble codes

Expected Behaviour
-----------------------------
Vehicle should continuously maintain lane center.

LKA should generate appropriate steering torque without entering FAULT state.

Expected Result
-----------------------------
No warning should appear.

Vehicle should remain centered inside the lane throughout the highway scenario.

Attachments
-----------------------------
1. Instrument Cluster Screenshot
2. Front Camera View
3. CANoe Signal Trace
""",
        comments=[
            """Comment 1 - Validation Team

Issue reproduced successfully in SIL environment.

Reproducibility:
10/10

No CAN communication errors observed.""",

"""Comment 2 - HIL Team

Issue also reproduced on HIL bench using production ECU.

Camera calibration verified.

Radar calibration verified.""",

"""Comment 3 - Software Team

Initial analysis indicates steering torque request gradually decreases before entering FAULT state.

No watchdog reset observed.""",

"""Comment 4 - Controls Team

Lane Offset signal continuously increases.

Steering torque command appears saturated near fault occurrence.

Need further investigation.""",

"""Comment 5 - Vehicle Dynamics Team

Yaw rate follows vehicle drift correctly.

No abnormal vehicle dynamics detected.

Mechanical steering inspection recommended.""",

"""Comment 6 - CAN Analysis

Bus load normal.

No frame loss.

No arbitration issue.

No CRC errors.""",

"""Comment 7 - Customer Feedback (Japanese)

高速道路走行中に約15分後、
LKAが正常に動作しなくなります。

車両は徐々に左へ逸脱します。

ドライバーが手動で操作しないと車線を維持できません。""",

"""Comment 8 - Developer

Need comparison with previous software version (v3.7.9).

Issue may be introduced after steering controller optimization.""",

"""Comment 9 - Root Cause Investigation

Possible modules involved:

• Steering Controller
• LKA Algorithm
• Lane Fusion Module
• Driver Override Logic
• Torque Limiter
• Fault Manager

Further investigation required.""",

"""Comment 10 - Status

Priority : High

Severity : Major

Customer Impact : High

Assigned Team : ADAS Controls

Current Status : Under Investigation"""],
        attachments=[
            "sample_images/lka_dashboard.png",
            "sample_images/lka_camera_view.png",
            "sample_images/graphic.png"

        ]
    )